#include QMK_KEYBOARD_H
#define END_CALL LCTL(LSFT(KC_H))
#define IGNORE_CALL LCTL(LSFT(KC_D))
#define SHARE_SCREEN LCTL(LSFT(KC_E))
#define RAISE_HAND LCTL(LSFT(KC_K))
#define START_VIDEO LCTL(LSFT(KC_A))
#define START_VOICE LCTL(LSFT(KC_S))
#define CAM_TOGGLE LCTL(LSFT(KC_O))
#define MUTE_TOGGLE LCTL(LSFT(KC_M))

enum layers {
  NORMAL_LAYER = 0
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [NORMAL_LAYER] = LAYOUT_ortho_2x4(
        END_CALL, IGNORE_CALL, SHARE_SCREEN, RAISE_HAND,
        START_VIDEO, START_VOICE, CAM_TOGGLE, MUTE_TOGGLE
    )
};
